---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  budgets-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Budgets Validation
    with:
      working-directory: modules/budgets

  team-budgets-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Team Budgets Validation
    with:
      enable-terraform-tests: true
      working-directory: modules/team-budgets
